apiVersion: v1
kind: Service
metadata:
  name: ping-coming-soon-page
  namespace: default
spec:
  selector:
    app: ping-coming-soon-page-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
